### ISSUE TITLE
Validating Argo workflow specs

### ISSUE THREAD

**Issue by edublancas** [argoproj-labs/argo-python-dsl#29]
Hi,

I'm developing a [library](https://github.com/ploomber/ploomber) that exports to Argo Workflows. I've been using this package as part of my testing suite to ensure my code produces valid YAML specs.

Argo workflows doesn't allow underscores in task names:

```
2021/03/20 13:19:15 Failed to submit workflow: templates.dag.tasks[1].name: 'sepal_area' is invalid: name must consist of alpha-numeric characters or '-', and must start with an alpha-numeric character (e.g. My-name1-2, 123-NAME)
```

But using this library does not yield any errors:

```python
from argo.workflows.dsl import Workflow

# does not raise errors
Workflow.from_dict(some_spec)
```

Is this expected? Is there a better way to validate Argo Workflow specs without having to install Argo? (I want to validate workflows as part of my CI pipeline).

Thanks!

**Comment by moshewe** [comment]
You can find an Argo jsonschema on their website, here:
https://argoproj.github.io/argo-workflows/ide-setup/

Just run your generated configs against it.

**Comment by edublancas** [comment]
Great! Thanks!

**Comment by moshewe** [comment]
see #31
