### ISSUE TITLE
Nested DAGs

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/argo-python-dsl#30]
**Description**

I have a scenario where I would like to encode a nested DAG using the DSL. More specifically, I have a task that uses a `with_items` decorator that, in turn, uses a template that is supposed to launch multiple processes that perform what I need them to perform. Is it syntactically possible to write a task that returns a template, which ultimately returns a closure for the parameter combination? In pseucode:

```python
@task
@with_items(['a', 'b', 'c'])
def A(...params) -> template:
   return B(...params)

@template # (??? is this the right choice?)
@with_items(['d', 'e', 'f'])
@inputs.param()  # (??? a, b, and c from step A)
def B(...params) -> script template
   return C(...all params)

@closure
@inputs.param(first)
@inputs.param(second)
def C(...params) -> script template:
  print(first / second)  # results in: ad, ae, af, bd, be, bf, cd, ce, cf
```

Final DAG:
```
           *
      /    |    \
     a     b      c
    /|\   /|\    /|\
    def   def    def
     \     |    /
ad, ae, af, bd, be, bf, cd, ce, cf (final steps)
          *          
```

Is this possible with the current version of the DSL? If so, what could be a way to structure the workflow?

**Additional context**

Argo: 3.0.1
Python: 3.7
K8S: 1.18 (GKE)

**Comment by moshewe** [comment]
See #18

**Comment by flaviuvadan** [comment]
Couler currently supports this through applications of `couler.concurrent` so I am closing this.
