### ISSUE TITLE
MAINTAINER NEEDED

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-python-dsl#33]
Please let me know if you want to.

**Comment by moshewe** [comment]
I'm interested.

**Comment by alexec** [comment]
@binarycrayon as the current maintainer, do you want help?

**Comment by binarycrayon** [comment]
@alexec sounds good. I lacked communication with you and the argo team while I worked on the SDK. Seeing the Argo workflow project promoting couler as the python sdk makes me believe there is no point maintaining the sdks from now on. Thanks!

**Comment by alexec** [comment]
No problem. CoulerProj has become popular quite quickly and seems well supported. I think we should probably push people in that direction.

**Comment by moshewe** [comment]
Wow, Couler looks nice! How come simple googling didn't find it relating to Argo?...

**Comment by alexec** [comment]
I think we'll archive this repo.
