### ISSUE TITLE
Relation to https://github.com/CermakM/argo-python-dsl

### ISSUE THREAD

**Issue by hadim** [argoproj-labs/argo-python-dsl#4]
Can you clarify how both repos (https://github.com/CermakM/argo-python-dsl and this one) are synced?

If the code is sync then what about issues and PRs? It would be nice to have a single source of truth.

**Comment by hadim** [comment]
ping @CermakM

**Comment by binarycrayon** [comment]
Hi I have taken over this project as a community maintainer. Original author Marek has moved on to better things.

I will consolidate the author's repo and merge updates.
